# Basket Analysis


**Definição**

O "Basket Analysis" (ou Análise de Cestas) é uma técnica de análise de dados usada em sistemas de recomendação e marketing para identificar associações e padrões de co-ocorrência de itens em transações de compra, registros de navegação ou outras interações dos usuários. O objetivo é descobrir quais itens são frequentemente comprados ou usados juntos, de modo que essas informações possam ser usadas para fazer recomendações personalizadas e criar estratégias de vendas mais eficazes.

O conceito central da Basket Analysis é o "princípio da co-ocorrência", que sugere que certos itens são frequentemente adquiridos simultaneamente por muitos usuários. Por exemplo, se um cliente compra uma câmera digital, é provável que também compre um cartão de memória e uma bolsa de transporte para a câmera. Ao analisar grandes conjuntos de dados de transações ou interações de usuários, a Basket Analysis pode identificar esses padrões e usar as associações encontradas para recomendar itens adicionais.

**Regra de associação chamada - Apriori**

Um algoritmo comum usado na Basket Analysis é a regra de associação chamada "Apriori". O algoritmo Apriori busca por conjuntos frequentes de itens e gera regras de associação, como "se um cliente compra X e Y, então é provável que também compre Z". Essas regras podem ser usadas para fazer recomendações de itens relacionados quando um cliente adiciona um produto ao carrinho de compras ou faz uma compra online.

A Basket Analysis é amplamente aplicada em várias áreas, incluindo comércio eletrônico, varejo, marketing, análise de redes sociais e muito mais. Além das recomendações de produtos, também pode ser usada para otimizar a disposição de produtos em lojas físicas, criar ofertas especiais ou pacotes de produtos e melhorar a segmentação de público-alvo em campanhas de marketing.

Entretanto, é importante notar que a Basket Analysis tem suas limitações. Ela se baseia em padrões históricos e não considera mudanças nas preferências do cliente ao longo do tempo. Outras técnicas de sistemas de recomendação, como filtragem colaborativa e recomendação baseada em conteúdo, podem ser usadas em conjunto com a Basket Analysis para fornecer recomendações mais precisas e diversificadas aos usuários.

# **Regra de associação**

Regra de associação é uma técnica de análise de dados frequentemente usada em mineração de dados e sistemas de recomendação para identificar padrões de co-ocorrência entre itens em um conjunto de dados. Essas regras ajudam a descobrir associações interessantes e úteis entre diferentes itens, permitindo inferir quais itens são frequentemente adquiridos juntos.

As regras de associação são geralmente expressas na forma de "se X, então Y", indicando que se um conjunto de itens X (conhecido como "antecedente" ou "item antecedente") está presente, é provável que outro conjunto de itens Y (conhecido como "consequente" ou "item consequente") também esteja presente.

Existem duas métricas principais usadas para medir a força e relevância das regras de associação:

Suporte (Support): Mede a frequência absoluta de ocorrência de uma regra em todo o conjunto de dados. É a proporção de transações em que a regra é verdadeira. Um alto suporte indica que a regra é frequente e relevante para o conjunto de dados.

Confiança (Confidence): Mede a probabilidade condicional de que o consequente ocorra, dado que o antecedente está presente. A confiança é calculada como a proporção do suporte da regra pelo suporte do antecedente. Uma alta confiança indica que a regra é altamente confiável.

Além disso, as regras de associação também podem ser avaliadas em termos de lift (elevação) e outras métricas, que ajudam a determinar se a associação entre os itens é significativa ou apenas uma coincidência.

Por exemplo, considere o seguinte conjunto de dados de transações de compra:


**Transação  Itens Comprados**


**1          {Pão, Leite}**

**2          {Pão, Ovos}**

**3          {Leite, Ovos}**

**4          {Pão, Leite, Ovos}**

**5          {Pão, Leite}**

Com base nesses dados, podemos gerar as seguintes regras de associação:

**{Pão} => {Leite} (suporte: 0.4, confiança: 0.8)**

**{Leite} => {Pão} (suporte: 0.4, confiança: 0.8)**

**{Pão} => {Ovos} (suporte: 0.4, confiança: 0.8)**

**{Ovos} => {Pão} (suporte: 0.4, confiança: 0.8)**

**{Leite} => {Ovos} (suporte: 0.4, confiança: 0.8)**

**{Ovos} => {Leite} (suporte: 0.4, confiança: 0.8)**


Essas regras mostram que pães, leite e ovos são frequentemente comprados juntos, com um suporte de 0.4 e uma confiança de 0.8. Isso indica uma forte associação entre esses itens, e essa informação pode ser usada, por exemplo, para fazer recomendações de itens relacionados ou planejar estratégias de venda cruzada em uma loja.

In [1]:
# Instalação pacote - algoritmo Apriori para realizar a Basket Analysis usando bibliotecas como pandas e mlxtend. 
! pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\rafae\anaconda3\lib\site-packages (0.22.0)
Requirement already satisfied: setuptools in c:\users\rafae\anaconda3\lib\site-packages (from mlxtend) (67.8.0)
Requirement already satisfied: joblib>=0.13.2 in c:\users\rafae\anaconda3\lib\site-packages (from mlxtend) (1.2.0)
Requirement already satisfied: scipy>=1.2.1 in c:\users\rafae\anaconda3\lib\site-packages (from mlxtend) (1.10.1)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\rafae\anaconda3\lib\site-packages (from mlxtend) (1.2.2)
Requirement already satisfied: numpy>=1.16.2 in c:\users\rafae\anaconda3\lib\site-packages (from mlxtend) (1.24.3)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\rafae\anaconda3\lib\site-packages (from mlxtend) (3.7.1)
Requirement already satisfied: pandas>=0.24.2 in c:\users\rafae\anaconda3\lib\site-packages (from mlxtend) (2.0.3)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\rafae\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (5.2.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\rafae\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (9.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\rafae\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\rafae\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.0.5)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\rafae\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\rafae\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\rafae\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\rafae\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\rafae\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: tzdata>=2022.1 in c:\users\rafae\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\rafae\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2022.7)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\rafae\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: zipp>=3.1.0 in c:\users\rafae\anaconda3\lib\site-packages (from importlib-resources>=3.2.0->matplotlib>=3.0.0->mlxtend) (3.11.0)
Requirement already satisfied: six>=1.5 in c:\users\rafae\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [2]:
# Carregando pacotes
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
# Exemplo de dados de compras
dados = {'Transação': [1, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 5, 5],
         'Item': ['A', 'B', 'C', 'A', 'B', 'A', 'C', 'B', 'C', 'D', 'E', 'B', 'C']}

# Converter os dados em um DataFrame
df = pd.DataFrame(dados)
df

    Transação Item
0           1    A
1           1    B
2           1    C
3           2    A
4           2    B
5           3    A
6           3    C
7           4    B
8           4    C
9           4    D
10          4    E
11          5    B
12          5    C

In [5]:
# Converter os dados para a matriz de cesta usando one-hot encoding
basket = (df.groupby(['Transação', 'Item'])['Item']
          .count().unstack().reset_index().fillna(0)
          .set_index('Transação'))
basket

Item         A    B    C    D    E
Transação
1          1.0  1.0  1.0  0.0  0.0
2          1.0  1.0  0.0  0.0  0.0
3          1.0  0.0  1.0  0.0  0.0
4          0.0  1.0  1.0  1.0  1.0
5          0.0  1.0  1.0  0.0  0.0

In [6]:
# Função para codificar os valores como 0 ou 1
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

# Aplicar a função de codificação aos dados da cesta
basket_sets = basket.applymap(encode_units)
basket_sets

Item       A  B  C  D  E
Transação
1          1  1  1  0  0
2          1  1  0  0  0
3          1  0  1  0  0
4          0  1  1  1  1
5          0  1  1  0  0

In [7]:
# Executar o algoritmo Apriori para encontrar os itens frequentes com suporte mínimo de 0.2
frequent_itemsets = apriori(basket_sets, 
                            min_support=0.2, 
                            use_colnames=True)
frequent_itemsets

C:\Users\rafae\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support      itemsets
0       0.6           (A)
1       0.8           (B)
2       0.8           (C)
3       0.2           (D)
4       0.2           (E)
5       0.4        (B, A)
6       0.4        (C, A)
7       0.6        (B, C)
8       0.2        (B, D)
9       0.2        (E, B)
10      0.2        (C, D)
11      0.2        (E, C)
12      0.2        (E, D)
13      0.2     (C, B, A)
14      0.2     (B, C, D)
15      0.2     (E, B, C)
16      0.2     (E, B, D)
17      0.2     (E, C, D)
18      0.2  (E, B, C, D)

In [10]:
# Gerar as regras de associação com confiança mínima de 0.7
rules = association_rules(frequent_itemsets, 
                          metric="confidence", 
                          min_threshold=0.7)
rules.head(5)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(B),(C),0.8,0.8,0.6,0.75,0.9375,-0.04,0.8,-0.25
1,(C),(B),0.8,0.8,0.6,0.75,0.9375,-0.04,0.8,-0.25
2,(D),(B),0.2,0.8,0.2,1.00,1.2500,0.04,inf,0.25
3,(E),(B),0.2,0.8,0.2,1.00,1.2500,0.04,inf,0.25
4,(D),(C),0.2,0.8,0.2,1.00,1.2500,0.04,inf,0.25

In [11]:
# Mostrar os itens frequentes
print("Itens frequentes:")
print(frequent_itemsets)

Itens frequentes:
    support      itemsets
0       0.6           (A)
1       0.8           (B)
2       0.8           (C)
3       0.2           (D)
4       0.2           (E)
5       0.4        (B, A)
6       0.4        (C, A)
7       0.6        (B, C)
8       0.2        (B, D)
9       0.2        (E, B)
10      0.2        (C, D)
11      0.2        (E, C)
12      0.2        (E, D)
13      0.2     (C, B, A)
14      0.2     (B, C, D)
15      0.2     (E, B, C)
16      0.2     (E, B, D)
17      0.2     (E, C, D)
18      0.2  (E, B, C, D)

In [12]:
# Mostrar as regras de associação
print("\nRegras de Associação:")
print(rules)

Regras de Associação:
   antecedents consequents  antecedent support  consequent support  support  \
0          (B)         (C)                 0.8                 0.8      0.6
1          (C)         (B)                 0.8                 0.8      0.6
2          (D)         (B)                 0.2                 0.8      0.2
3          (E)         (B)                 0.2                 0.8      0.2
4          (D)         (C)                 0.2                 0.8      0.2
5          (E)         (C)                 0.2                 0.8      0.2
6          (E)         (D)                 0.2                 0.2      0.2
7          (D)         (E)                 0.2                 0.2      0.2
8       (B, D)         (C)                 0.2                 0.8      0.2
9       (C, D)         (B)                 0.2                 0.8      0.2
10         (D)      (B, C)                 0.2                 0.6      0.2
11      (E, B)         (C)                 0.2                 0.8      0.2
12      (E, C)         (B)                 0.2                 0.8      0.2
13         (E)      (B, C)                 0.2                 0.6      0.2
14      (E, B)         (D)                 0.2                 0.2      0.2
15      (E, D)         (B)                 0.2                 0.8      0.2
16      (B, D)         (E)                 0.2                 0.2      0.2
17         (E)      (B, D)                 0.2                 0.2      0.2
18         (D)      (E, B)                 0.2                 0.2      0.2
19      (E, C)         (D)                 0.2                 0.2      0.2
20      (E, D)         (C)                 0.2                 0.8      0.2
21      (C, D)         (E)                 0.2                 0.2      0.2
22         (E)      (C, D)                 0.2                 0.2      0.2
23         (D)      (E, C)                 0.2                 0.2      0.2
24   (E, B, C)         (D)                 0.2                 0.2      0.2
25   (E, B, D)         (C)                 0.2                 0.8      0.2
26   (E, C, D)         (B)                 0.2                 0.8      0.2
27   (B, C, D)         (E)                 0.2                 0.2      0.2
28      (E, B)      (C, D)                 0.2                 0.2      0.2
29      (E, C)      (B, D)                 0.2                 0.2      0.2
30      (E, D)      (B, C)                 0.2                 0.6      0.2
31      (B, D)      (E, C)                 0.2                 0.2      0.2
32      (C, D)      (E, B)                 0.2                 0.2      0.2
33         (E)   (B, C, D)                 0.2                 0.2      0.2
34         (D)   (E, B, C)                 0.2                 0.2      0.2

    confidence      lift  leverage  conviction  zhangs_metric
0         0.75  0.937500     -0.04         0.8          -0.25
1         0.75  0.937500     -0.04         0.8          -0.25
2         1.00  1.250000      0.04         inf           0.25
3         1.00  1.250000      0.04         inf           0.25
4         1.00  1.250000      0.04         inf           0.25
5         1.00  1.250000      0.04         inf           0.25
6         1.00  5.000000      0.16         inf           1.00
7         1.00  5.000000      0.16         inf           1.00
8         1.00  1.250000      0.04         inf           0.25
9         1.00  1.250000      0.04         inf           0.25
10        1.00  1.666667      0.08         inf           0.50
11        1.00  1.250000      0.04         inf           0.25
12        1.00  1.250000      0.04         inf           0.25
13        1.00  1.666667      0.08         inf           0.50
14        1.00  5.000000      0.16         inf           1.00
15        1.00  1.250000      0.04         inf           0.25
16        1.00  5.000000      0.16         inf           1.00
17        1.00  5.000000      0.16         inf           1.00
18        1.00  5.000000      0.16         inf           1.00
19        1.00  5.000000      0.16         inf           1.00
20        1.00  1.250000      0.04         inf           0.25
21        1.00  5.000000      0.16         inf           1.00
22        1.00  5.000000      0.16         inf           1.00
23        1.00  5.000000      0.16         inf           1.00
24        1.00  5.000000      0.16         inf           1.00
25        1.00  1.250000      0.04         inf           0.25
26        1.00  1.250000      0.04         inf           0.25
27        1.00  5.000000      0.16         inf           1.00
28        1.00  5.000000      0.16         inf           1.00
29        1.00  5.000000      0.16         inf           1.00
30        1.00  1.666667      0.08         inf           0.50
31        1.00  5.000000      0.16         inf           1.00
32        1.00  5.000000      0.16         inf           1.00
33        1.00  5.000000      0.16         inf           1.00
34        1.00  5.000000      0.16         inf           1.00